[package]
name = "versionator"
version = "0.1.0"
authors = ["Daniel Schemmel <daniel.schemmel@comsys.rwth-aachen.de>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
versionator-common = { path = "../versionator-common" }
versionator-proc = { path = "../versionator-proc" }
