# See https://rust-lang.github.io/rustfmt/ for all possible settings & documentation.

# When running `cargo fmt`, we don't need to set this option because it will be picked up from cargo. However, this
# explicit setting is useful for (IDE) tools that run `rustfmt` directly, which otherwise default to "2015".
edition = "2021"

max_width = 120
hard_tabs = true
tab_spaces = 2
newline_style = "Unix"

# comment_width = 120
# wrap_comments = true

# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

use_field_init_shorthand = true
