[package]
name = "sample"
version = "0.0.0"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = false

[dependencies]
build-info = { path = "../build-info" }

[build-dependencies]
build-info-build = { path = "../build-info-build" }
