[package]
name = "sample"
version = "0.0.1-alpha.1"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = false
repository = "https://github.com/danielschemmel/build-info/"

[dependencies]
build-info = { path = "../build-info" }

[build-dependencies]
build-info-build = { path = "../build-info-build" }
