[package]
name = "sample"
version = "0.1.0"
authors = ["Daniel Schemmel <daniel.schemmel@comsys.rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
versionator = { path = "../versionator" }
versionator-build = { path = "../versionator-build" }

[build-dependencies]
versionator-build = { path = "../versionator-build" }
